In [1]:
!pip install numpy

In [2]:
import numpy as np

In [6]:
list1=[1,2,3]
print(list1)

[1, 2, 3]


In [16]:
arr_list1=np.array(list1)
print(arr_list1)
print(arr_list1.ndim)

[1 2 3]
1


In [17]:
list1=[1,2,3]
list2=[4,5,6]
arr_list2=np.array([list1, list2])
print(arr_list2)
print(arr_list2.ndim)

[[1 2 3]
 [4 5 6]]
2


In [15]:
list1=[1,2,3]
list2=[4,5,6]
list3=[7,8,9]
arr_list3=np.array([[list1,list2,list3]])
print(arr_list3)
print(arr_list3.ndim)

[[[1 2 3]
  [4 5 6]]]
3
