In [1]:
import numpy as np
list1=[1, 2, 3]
list2=[4,5,6]
list3=[7,8,6]
numpyarr=np.array([[list1,list2,list3]])
print(numpyarr)

[[[1 2 3]
  [4 5 6]
  [7 8 6]]]


## Numpy array attribute

In [4]:
num_att=np.array([[1,2,3],[5,6,7]])
print(num_att)

[[1 2 3]
 [5 6 7]]


In [6]:
print("Shape:",num_att.shape)
print("Size:",num_att.size)
print("type:",type(num_att))
print("data type:",num_att.dtype)
print("Dimension:",num_att.ndim)

Shape: (2, 3)
Size: 6
type: <class 'numpy.ndarray'>
data type: int64
Dimension: 2


In [17]:
arr1=np.array([1,2,3,4])
arr2=np.array([[[2,3,4],[2,4,5],[7,8,6]]])
print(arr1,"\n")
print(arr2,"\n")

print("For array 1:")
print("Shape:", arr1.shape)
print("Size:", arr1.size)
print("Dimension", arr1.ndim)
print("Data Type:", arr1.dtype)

print("\nFor array 2:")
print("Shape:", arr2.shape)
print("Size:", arr2.size)
print("Dimension", arr2.ndim)
print("Data Type:", arr2.dtype)


[1 2 3 4] 

[[[5 6 9]
  [2 3 4]
  [2 4 5]
  [7 8 6]]] 

For array 1:
Shape: (4,)
Size: 4
Dimension 1
Data Type: int64

For array 2:
Shape: (1, 4, 3)
Size: 12
Dimension 3
Data Type: int64


In [23]:
#Zero array
zero=np.zeros((3,4))
print(zero)
# here 3 is the row no 4 is the column no.how many rows and column would be 
# needed

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [24]:
#One array
one=np.ones((3,4))
print(one)
# here 3 is the row no 4 is the column no.how many rows and column would be 
# needed

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [26]:
#full array
full1=np.full((3,4),11)
print(full1)
# here 3 is the row no 4 is the column no.how many rows and column would be 
# needed and 11 is what number we want to print

[[11 11 11 11]
 [11 11 11 11]
 [11 11 11 11]]


In [31]:
#one array using full array
full2=np.full((3,4),1)
print(full2)


[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [33]:
#zero array using full array
full2=np.full((3,4),0)
print(full2)


[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
